### ISSUE TITLE
Integrate with Azure Devops Server

### ISSUE THREAD

**Issue by gardebring** [acraven/azure-dependabot#6]
Has anyone tried this towards an Azure Devops Server (the on-premise version)?
I am doing a docker build of the Dockerfile to try this locally and I am getting this:
```
Step 7/8 : COPY . .
 ---> f5f54c5cdc51
Step 8/8 : RUN bundle exec ruby ./update.rb
 ---> Running in 2ad1ac649015
/usr/local/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/ (JSON::ParserError)d">




<html lang="en-US">
<head><title>

            Azure DevOps Services | Sign In

....[cut html output short for brevity]....
</body>
</html>
'
        from /usr/local/lib/ruby/2.6.0/json/common.rb:156:in `parse'
        from /usr/local/bundle/gems/dependabot-common-0.111.59/lib/dependabot/clients/azure.rb:47:in `fetch_default_branch'
        from /usr/local/bundle/gems/dependabot-common-0.111.59/lib/dependabot/file_fetchers/base.rb:368:in `default_branch_for_repo'
        from /usr/local/bundle/gems/dependabot-common-0.111.59/lib/dependabot/file_fetchers/base.rb:57:in `commit'
        from /usr/local/bundle/gems/dependabot-common-0.111.59/lib/dependabot/file_fetchers/base.rb:285:in `_full_specification_for'
        from /usr/local/bundle/gems/dependabot-common-0.111.59/lib/dependabot/file_fetchers/base.rb:121:in `_fetch_repo_contents'
        from /usr/local/bundle/gems/dependabot-common-0.111.59/lib/dependabot/file_fetchers/base.rb:106:in `repo_contents'
        from /usr/local/bundle/gems/dependabot-nuget-0.111.59/lib/dependabot/nuget/file_fetcher.rb:179:in `csproj_file'
        from /usr/local/bundle/gems/dependabot-nuget-0.111.59/lib/dependabot/nuget/file_fetcher.rb:56:in `project_files'
        from /usr/local/bundle/gems/dependabot-nuget-0.111.59/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
        from /usr/local/bundle/gems/dependabot-common-0.111.59/lib/dependabot/file_fetchers/base.rb:53:in `files'
        from ./update.rb:28:in `<main>'
The command '/bin/sh -c bundle exec ruby ./update.rb' returned a non-zero code: 1
```
.. and so on.
It seems I am getting an Azure Devops authentication page.
My update.rb-file has the following configuration:
```
repo = "DefaultCollection/ProjectName/_git/RepoName"

credentials = [{
  "type" => "git_source",
  "host" => "hostname.of.machine",
  "username" => "",
  "password" => "AZURE_DEVOPS_PAT"
},{
  "type" => "nuget_feed",
  "url" => "https://hostname.of.machine/DefaultCollection/_packaging/InternalFeed/nuget/v3/index.json",
  "token" => ":AZURE_DEVOPS_PAT"
}]
```

Any ideas? I am running the docker build from a windows 10 machine.

**Comment by jlkweb12** [comment]
Did you ever find a solution for this?

**Comment by gardebring** [comment]
> Did you ever find a solution for this?

Hi. I unfortunately did not, we ended up with using renovate instead.
I wrote a guide for how to set that up which you can find here:
https://www.linkedin.com/pulse/keeping-package-dependencies-up-date-azure-devops-anders-gardebring/

**Comment by mburumaxwell** [comment]
Hey @jlkweb12 , @gardebring , May be you can try an extension that's still in the works?

https://marketplace.visualstudio.com/items?itemName=tingle-software.dependabot
